import { type NigerianState } from '../types';

export const NIGERIAN_STATES: NigerianState[] = [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
    'Federal Capital Territory - Abuja'
];

export const STATE_ABBREVIATIONS: Record<NigerianState, string> = {
    'Abia': 'AB',
    'Adamawa': 'AD',
    'Akwa Ibom': 'AK',
    'Anambra': 'AN',
    'Bauchi': 'BA',
    'Bayelsa': 'BY',
    'Benue': 'BE',
    'Borno': 'BO',
    'Cross River': 'CR',
    'Delta': 'DE',
    'Ebonyi': 'EB',
    'Edo': 'ED',
    'Ekiti': 'EK',
    'Enugu': 'EN',
    'Gombe': 'GO',
    'Imo': 'IM',
    'Jigawa': 'JI',
    'Kaduna': 'KD',
    'Kano': 'KN',
    'Katsina': 'KT',
    'Kebbi': 'KE',
    'Kogi': 'KO',
    'Kwara': 'KW',
    'Lagos': 'LA',
    'Nasarawa': 'NA',
    'Niger': 'NI',
    'Ogun': 'OG',
    'Ondo': 'ON',
    'Osun': 'OS',
    'Oyo': 'OY',
    'Plateau': 'PL',
    'Rivers': 'RI',
    'Sokoto': 'SO',
    'Taraba': 'TA',
    'Yobe': 'YO',
    'Zamfara': 'ZA',
    'Federal Capital Territory - Abuja': 'FCT'
};